---
title: "Stat250-S25"
format: html
---

Landing page for Stat250 course materials in Spring 2025

# In-Class Materials

Day02: [slides](/slides/02/slides02.html) [handout](/notes/02-permutation/notes02.pdf) [r code](/notes/02-permutation/activity02.html)

Day03: [handout](/notes/03-sampling-dists/notes03.pdf) [activity qmd](/notes/03-sampling-dists/activity03.html)

Day04: [slides](/slides/04/slides04.html) | [handout](/notes/04-probability/04-probability.pdf)

Day05: [slides](/slides/05/slides05.html) | [handout](/notes/05-mle/05-notes.pdf)

Day06: [slides](/slides/06/slides06.html) | [handout](/notes/06-mle-2/notes06.pdf)

Day07: [slides](/slides/07/slides07.html) | [handout](/notes/07-mom/notes07.pdf)

Day08: [slides](/slides/08/slides08.html) | [handout](/notes/08-bias-variance/notes08.pdf)

Day09: [slides](/slides/09/slides09.html) | [handout](/notes/09-crlb/notes09.pdf)

Day10: [handout](/notes/10-asymptotics/notes10.pdf) | [R activity](/notes/10-asymptotics/activity10.html)

Day11: [handout](/notes/11-review/notes11.pdf) 

Day12:  Exam I [corrections info](/notes/exam01-corrections/exam01-corrections.pdf)

Day13: [slides](/slides/13/slides13.html) | [handout](/notes/13-intro-ci/notes13.pdf) | [R activity](/notes/13-intro-ci/activity13.html)

Day14: [slides](/slides/14/slides14.html) | [handout](/notes/14-clt-ci/notes14.pdf) 

Day15: [handout](/notes/15-ci-pivot/notes15.pdf) 

Day16: [handout](/notes/16-bootstrap-t/notes16-h.pdf) | [R activity](/notes/16-bootstrap-t/16-activity.html) | [slides](/slides/16/slides16.html) 

Day17: [handout](/notes/17-two-sample-ci/notes17.pdf) | [R activity](/notes/17-two-sample-ci/17-activity.html) | [slides](/slides/17/slides17.html) 

Day18: [handout](/notes/18-intro-to-ht/notes18.pdf) | 

Day19: [handout](/notes/19-errors-power/notes19.pdf) | [slides](/slides/19/slides19.html)

Day20: [handout](/notes/20-ht-ci-connection/notes20.pdf) 

Day21: [handout](/notes/21-lrts/notes21.pdf) 

Day22: [handout](/notes/22-multiple-testing-and-review/notes22.pdf) | [slides](/slides/22/slides22.html) | [Exam 02 Review](/notes/22-multiple-testing-and-review/exam02-topics.pdf)

Day23: Exam II | Exam II [corrections info](/notes/exam01-corrections/exam02-corrections.pdf)

Day24: [handout](/notes/24/notes24.pdf) | [slides](/slides/24/slides24.html) 

Day25: [handout](/notes/25-least-squares/notes25.pdf) 

Day26: [handout](/notes/26-slr-inference/notes26.pdf) 

Day27: [handout](/notes/27-intro-bayes/notes27.pdf) | [slides](/slides/27/slides27.html) 

# Project

[Proposal Info and Rubric](/notes/project/project.pdf) 

[Project Topic Ideas](/notes/project/proj-ideas.html) (*Note:* Will continue to be updated) 

# Other Resources and Readings

- [R Basics](readings/r-basics.html)
- How to do [homework in R in Stat250](readings/r-homework-stat250.html)
